// Auto-generated by scripts/fetch_presets.py — do not edit manually.
// To refresh: start the backend then run: python scripts/fetch_presets.py
import type { RoutesResponse } from "@/types/api";

export const PRESET_CACHE: Record<string, RoutesResponse> = {
  "orchard road, singapore|marina bay, singapore|driving": {
    "origin": "Orchard Rd, Singapore",
    "destination": "Marina Bay, Singapore",
    "routes": [
      {
        "index": 0,
        "summary": "Orchard Rd and Bras Basah Rd",
        "distance": "4.1 km",
        "duration_current": "11 mins",
        "duration_typical": "11 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 7.9
          },
          {
            "hour": "06:00",
            "duration_minutes": 8.3
          },
          {
            "hour": "07:00",
            "duration_minutes": 8.1
          },
          {
            "hour": "08:00",
            "duration_minutes": 8.6
          },
          {
            "hour": "09:00",
            "duration_minutes": 9.8
          },
          {
            "hour": "10:00",
            "duration_minutes": 11.0
          },
          {
            "hour": "11:00",
            "duration_minutes": 12.5
          },
          {
            "hour": "12:00",
            "duration_minutes": 14.6
          },
          {
            "hour": "13:00",
            "duration_minutes": 15.1
          },
          {
            "hour": "14:00",
            "duration_minutes": 15.0
          },
          {
            "hour": "15:00",
            "duration_minutes": 14.1
          },
          {
            "hour": "16:00",
            "duration_minutes": 14.4
          },
          {
            "hour": "17:00",
            "duration_minutes": 14.4
          },
          {
            "hour": "18:00",
            "duration_minutes": 14.7
          },
          {
            "hour": "19:00",
            "duration_minutes": 14.7
          },
          {
            "hour": "20:00",
            "duration_minutes": 11.4
          },
          {
            "hour": "21:00",
            "duration_minutes": 11.3
          },
          {
            "hour": "22:00",
            "duration_minutes": 11.8
          },
          {
            "hour": "23:00",
            "duration_minutes": 9.6
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 1,
        "summary": "Orchard Rd",
        "distance": "5.3 km",
        "duration_current": "14 mins",
        "duration_typical": "14 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 10.1
          },
          {
            "hour": "06:00",
            "duration_minutes": 10.4
          },
          {
            "hour": "07:00",
            "duration_minutes": 10.7
          },
          {
            "hour": "08:00",
            "duration_minutes": 11.4
          },
          {
            "hour": "09:00",
            "duration_minutes": 12.7
          },
          {
            "hour": "10:00",
            "duration_minutes": 13.6
          },
          {
            "hour": "11:00",
            "duration_minutes": 14.8
          },
          {
            "hour": "12:00",
            "duration_minutes": 17.9
          },
          {
            "hour": "13:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "14:00",
            "duration_minutes": 18.4
          },
          {
            "hour": "15:00",
            "duration_minutes": 17.8
          },
          {
            "hour": "16:00",
            "duration_minutes": 18.3
          },
          {
            "hour": "17:00",
            "duration_minutes": 18.1
          },
          {
            "hour": "18:00",
            "duration_minutes": 18.2
          },
          {
            "hour": "19:00",
            "duration_minutes": 17.7
          },
          {
            "hour": "20:00",
            "duration_minutes": 14.3
          },
          {
            "hour": "21:00",
            "duration_minutes": 14.1
          },
          {
            "hour": "22:00",
            "duration_minutes": 15.8
          },
          {
            "hour": "23:00",
            "duration_minutes": 13.1
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 2,
        "summary": "Republic Ave",
        "distance": "7.7 km",
        "duration_current": "16 mins",
        "duration_typical": "16 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 11.1
          },
          {
            "hour": "06:00",
            "duration_minutes": 11.4
          },
          {
            "hour": "07:00",
            "duration_minutes": 12.7
          },
          {
            "hour": "08:00",
            "duration_minutes": 13.6
          },
          {
            "hour": "13:00",
            "duration_minutes": 20.4
          },
          {
            "hour": "14:00",
            "duration_minutes": 19.0
          },
          {
            "hour": "15:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "16:00",
            "duration_minutes": 17.9
          },
          {
            "hour": "17:00",
            "duration_minutes": 17.9
          },
          {
            "hour": "18:00",
            "duration_minutes": 19.1
          },
          {
            "hour": "19:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "21:00",
            "duration_minutes": 15.7
          },
          {
            "hour": "22:00",
            "duration_minutes": 16.5
          },
          {
            "hour": "23:00",
            "duration_minutes": 14.3
          }
        ],
        "transit_legs": null,
        "transfers": null
      }
    ]
  },
  "dhoby ghaut, singapore|changi airport, singapore|driving": {
    "origin": "Dhoby Ghaut, Singapore",
    "destination": "60 Airport Blvd., Singapore Changi Airport (SIN), Singapore 819643",
    "routes": [
      {
        "index": 0,
        "summary": "ECP",
        "distance": "20.0 km",
        "duration_current": "23 mins",
        "duration_typical": "23 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 18.5
          },
          {
            "hour": "06:00",
            "duration_minutes": 19.1
          },
          {
            "hour": "07:00",
            "duration_minutes": 21.0
          },
          {
            "hour": "08:00",
            "duration_minutes": 21.5
          },
          {
            "hour": "09:00",
            "duration_minutes": 22.4
          },
          {
            "hour": "10:00",
            "duration_minutes": 22.6
          },
          {
            "hour": "11:00",
            "duration_minutes": 23.4
          },
          {
            "hour": "12:00",
            "duration_minutes": 24.1
          },
          {
            "hour": "13:00",
            "duration_minutes": 24.6
          },
          {
            "hour": "14:00",
            "duration_minutes": 24.3
          },
          {
            "hour": "15:00",
            "duration_minutes": 25.7
          },
          {
            "hour": "16:00",
            "duration_minutes": 25.2
          },
          {
            "hour": "17:00",
            "duration_minutes": 25.9
          },
          {
            "hour": "18:00",
            "duration_minutes": 26.4
          },
          {
            "hour": "19:00",
            "duration_minutes": 25.6
          },
          {
            "hour": "20:00",
            "duration_minutes": 23.4
          },
          {
            "hour": "21:00",
            "duration_minutes": 22.9
          },
          {
            "hour": "22:00",
            "duration_minutes": 23.4
          },
          {
            "hour": "23:00",
            "duration_minutes": 22.1
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 1,
        "summary": "PIE",
        "distance": "21.2 km",
        "duration_current": "25 mins",
        "duration_typical": "23 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 19.4
          },
          {
            "hour": "06:00",
            "duration_minutes": 20.1
          },
          {
            "hour": "07:00",
            "duration_minutes": 21.8
          },
          {
            "hour": "08:00",
            "duration_minutes": 22.2
          },
          {
            "hour": "09:00",
            "duration_minutes": 23.3
          },
          {
            "hour": "10:00",
            "duration_minutes": 23.5
          },
          {
            "hour": "11:00",
            "duration_minutes": 24.6
          },
          {
            "hour": "12:00",
            "duration_minutes": 25.2
          },
          {
            "hour": "13:00",
            "duration_minutes": 25.9
          },
          {
            "hour": "14:00",
            "duration_minutes": 25.9
          },
          {
            "hour": "15:00",
            "duration_minutes": 27.2
          },
          {
            "hour": "16:00",
            "duration_minutes": 26.7
          },
          {
            "hour": "17:00",
            "duration_minutes": 27.0
          },
          {
            "hour": "18:00",
            "duration_minutes": 27.4
          },
          {
            "hour": "19:00",
            "duration_minutes": 25.6
          },
          {
            "hour": "20:00",
            "duration_minutes": 24.7
          },
          {
            "hour": "21:00",
            "duration_minutes": 24.9
          },
          {
            "hour": "22:00",
            "duration_minutes": 26.1
          },
          {
            "hour": "23:00",
            "duration_minutes": 23.1
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 2,
        "summary": "Central Expw. and PIE",
        "distance": "23.3 km",
        "duration_current": "24 mins",
        "duration_typical": "24 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 20.0
          },
          {
            "hour": "06:00",
            "duration_minutes": 20.9
          },
          {
            "hour": "07:00",
            "duration_minutes": 22.7
          },
          {
            "hour": "08:00",
            "duration_minutes": 22.8
          },
          {
            "hour": "09:00",
            "duration_minutes": 23.9
          },
          {
            "hour": "10:00",
            "duration_minutes": 24.2
          },
          {
            "hour": "11:00",
            "duration_minutes": 25.3
          },
          {
            "hour": "12:00",
            "duration_minutes": 25.9
          },
          {
            "hour": "13:00",
            "duration_minutes": 27.1
          },
          {
            "hour": "14:00",
            "duration_minutes": 26.5
          },
          {
            "hour": "15:00",
            "duration_minutes": 27.7
          },
          {
            "hour": "16:00",
            "duration_minutes": 27.0
          },
          {
            "hour": "17:00",
            "duration_minutes": 27.1
          },
          {
            "hour": "18:00",
            "duration_minutes": 26.9
          },
          {
            "hour": "20:00",
            "duration_minutes": 24.2
          },
          {
            "hour": "21:00",
            "duration_minutes": 24.3
          },
          {
            "hour": "22:00",
            "duration_minutes": 26.8
          },
          {
            "hour": "23:00",
            "duration_minutes": 24.0
          }
        ],
        "transit_legs": null,
        "transfers": null
      }
    ]
  },
  "macritchie reservoir, singapore|singapore zoo, singapore|driving": {
    "origin": "MacRitchie Reservoir, Singapore",
    "destination": "80 Mandai Lake Rd, Singapore 729826",
    "routes": [
      {
        "index": 0,
        "summary": "Bukit Timah Expy",
        "distance": "15.6 km",
        "duration_current": "18 mins",
        "duration_typical": "18 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 15.3
          },
          {
            "hour": "06:00",
            "duration_minutes": 16.1
          },
          {
            "hour": "07:00",
            "duration_minutes": 16.9
          },
          {
            "hour": "08:00",
            "duration_minutes": 17.5
          },
          {
            "hour": "09:00",
            "duration_minutes": 18.6
          },
          {
            "hour": "10:00",
            "duration_minutes": 19.4
          },
          {
            "hour": "11:00",
            "duration_minutes": 18.9
          },
          {
            "hour": "12:00",
            "duration_minutes": 18.6
          },
          {
            "hour": "13:00",
            "duration_minutes": 18.6
          },
          {
            "hour": "14:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "15:00",
            "duration_minutes": 19.7
          },
          {
            "hour": "16:00",
            "duration_minutes": 19.9
          },
          {
            "hour": "17:00",
            "duration_minutes": 20.4
          },
          {
            "hour": "18:00",
            "duration_minutes": 19.2
          },
          {
            "hour": "19:00",
            "duration_minutes": 19.1
          },
          {
            "hour": "20:00",
            "duration_minutes": 18.1
          },
          {
            "hour": "21:00",
            "duration_minutes": 18.1
          },
          {
            "hour": "22:00",
            "duration_minutes": 17.6
          },
          {
            "hour": "23:00",
            "duration_minutes": 16.6
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 1,
        "summary": "PIE and Bukit Timah Expy",
        "distance": "17.2 km",
        "duration_current": "19 mins",
        "duration_typical": "19 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 16.2
          },
          {
            "hour": "06:00",
            "duration_minutes": 17.3
          },
          {
            "hour": "07:00",
            "duration_minutes": 18.2
          },
          {
            "hour": "08:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "09:00",
            "duration_minutes": 19.8
          },
          {
            "hour": "10:00",
            "duration_minutes": 20.6
          },
          {
            "hour": "11:00",
            "duration_minutes": 20.1
          },
          {
            "hour": "12:00",
            "duration_minutes": 19.7
          },
          {
            "hour": "13:00",
            "duration_minutes": 19.9
          },
          {
            "hour": "15:00",
            "duration_minutes": 20.8
          },
          {
            "hour": "16:00",
            "duration_minutes": 21.0
          },
          {
            "hour": "17:00",
            "duration_minutes": 21.6
          },
          {
            "hour": "18:00",
            "duration_minutes": 20.3
          },
          {
            "hour": "19:00",
            "duration_minutes": 20.2
          },
          {
            "hour": "20:00",
            "duration_minutes": 19.1
          },
          {
            "hour": "21:00",
            "duration_minutes": 18.9
          },
          {
            "hour": "23:00",
            "duration_minutes": 17.6
          }
        ],
        "transit_legs": null,
        "transfers": null
      },
      {
        "index": 2,
        "summary": "Upper Thomson Rd",
        "distance": "15.8 km",
        "duration_current": "22 mins",
        "duration_typical": "22 mins",
        "hourly_traffic": [
          {
            "hour": "05:00",
            "duration_minutes": 18.7
          },
          {
            "hour": "06:00",
            "duration_minutes": 21.1
          },
          {
            "hour": "07:00",
            "duration_minutes": 21.3
          },
          {
            "hour": "08:00",
            "duration_minutes": 21.8
          },
          {
            "hour": "09:00",
            "duration_minutes": 23.5
          },
          {
            "hour": "10:00",
            "duration_minutes": 23.8
          },
          {
            "hour": "11:00",
            "duration_minutes": 24.7
          },
          {
            "hour": "12:00",
            "duration_minutes": 23.9
          },
          {
            "hour": "13:00",
            "duration_minutes": 23.6
          },
          {
            "hour": "14:00",
            "duration_minutes": 23.6
          },
          {
            "hour": "15:00",
            "duration_minutes": 24.0
          },
          {
            "hour": "16:00",
            "duration_minutes": 22.9
          },
          {
            "hour": "17:00",
            "duration_minutes": 22.8
          },
          {
            "hour": "18:00",
            "duration_minutes": 23.2
          },
          {
            "hour": "19:00",
            "duration_minutes": 22.7
          },
          {
            "hour": "20:00",
            "duration_minutes": 22.1
          },
          {
            "hour": "21:00",
            "duration_minutes": 21.6
          },
          {
            "hour": "22:00",
            "duration_minutes": 20.9
          },
          {
            "hour": "23:00",
            "duration_minutes": 19.6
          }
        ],
        "transit_legs": null,
        "transfers": null
      }
    ]
  }
};
