#!/usr/bin/env python3
"""
Fetch the three preset routes from the local API and write
frontend/src/data/presets.ts with the baked responses.

Usage (from repo root, with backend running at localhost:8000):
    source .venv/bin/activate
    python main.py &           # start backend if not already running
    python scripts/fetch_presets.py
    # commit the updated frontend/src/data/presets.ts
"""
import json
import sys
from pathlib import Path

try:
    import httpx
except ImportError:
    sys.exit("httpx not found — activate the backend venv first: source .venv/bin/activate")

API = "http://localhost:8000"

PRESETS = [
    ("Orchard Road, Singapore", "Marina Bay, Singapore", "driving"),
    ("Dhoby Ghaut, Singapore", "Changi Airport, Singapore", "driving"),
    ("MacRitchie Reservoir, Singapore", "Singapore Zoo, Singapore", "driving"),
]

OUT = Path(__file__).parent.parent / "frontend" / "src" / "data" / "presets.ts"


def main() -> None:
    cache: dict[str, object] = {}

    for origin, destination, mode in PRESETS:
        print(f"Fetching  {origin} → {destination} ({mode}) …")
        try:
            resp = httpx.post(
                f"{API}/api/routes",
                json={"origin": origin, "destination": destination, "mode": mode},
                timeout=60,
            )
            resp.raise_for_status()
        except httpx.ConnectError:
            sys.exit(f"\nCould not connect to {API} — is the backend running?")

        data = resp.json()
        key = f"{origin.strip().lower()}|{destination.strip().lower()}|{mode}"
        cache[key] = data
        print(f"  ✓  {len(data['routes'])} routes")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    ts = "\n".join([
        "// Auto-generated by scripts/fetch_presets.py — do not edit manually.",
        "// To refresh: start the backend then run: python scripts/fetch_presets.py",
        "import type { RoutesResponse } from \"@/types/api\";",
        "",
        f"export const PRESET_CACHE: Record<string, RoutesResponse> = {json.dumps(cache, indent=2)};",
        "",
    ])

    OUT.write_text(ts)
    print(f"\nWrote {OUT.relative_to(Path.cwd())}")
    print("Commit the file and redeploy to make the presets permanent.")


if __name__ == "__main__":
    main()
